/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as PendentesRouteImport } from './routes/pendentes'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEventosRouteImport } from './routes/admin/eventos'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as TarefasIndexRouteImport } from './routes/tarefas/index'
import { Route as TarefasAgendaRouteImport } from './routes/tarefas/agenda'
import { Route as TarefasCalendarioRouteImport } from './routes/tarefas/calendario'
import { Route as TarefasMeuDiaRouteImport } from './routes/tarefas/meu-dia'
import { Route as TarefasMinhasRouteImport } from './routes/tarefas/minhas'
import { Route as TarefasTodasRouteImport } from './routes/tarefas/todas'
import { Route as ApiCaktoWebhookRouteImport } from './routes/api/cakto/webhook'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiGoogleSyncRouteImport } from './routes/api/google/sync'
import { Route as TarefasEspacosIndexRouteImport } from './routes/tarefas/espacos/index'
import { Route as TarefasEspacosSpaceIdRouteImport } from './routes/tarefas/espacos/$spaceId'
import { Route as TarefasQuadrosBoardIdRouteImport } from './routes/tarefas/quadros/$boardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const PendentesRoute = PendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/admin/eventos',
  path: '/admin/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasIndexRoute = TarefasIndexRouteImport.update({
  id: '/tarefas/',
  path: '/tarefas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasAgendaRoute = TarefasAgendaRouteImport.update({
  id: '/tarefas/agenda',
  path: '/tarefas/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasCalendarioRoute = TarefasCalendarioRouteImport.update({
  id: '/tarefas/calendario',
  path: '/tarefas/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasMeuDiaRoute = TarefasMeuDiaRouteImport.update({
  id: '/tarefas/meu-dia',
  path: '/tarefas/meu-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasMinhasRoute = TarefasMinhasRouteImport.update({
  id: '/tarefas/minhas',
  path: '/tarefas/minhas',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasTodasRoute = TarefasTodasRouteImport.update({
  id: '/tarefas/todas',
  path: '/tarefas/todas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaktoWebhookRoute = ApiCaktoWebhookRouteImport.update({
  id: '/api/cakto/webhook',
  path: '/api/cakto/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleSyncRoute = ApiGoogleSyncRouteImport.update({
  id: '/api/google/sync',
  path: '/api/google/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasEspacosIndexRoute = TarefasEspacosIndexRouteImport.update({
  id: '/tarefas/espacos/',
  path: '/tarefas/espacos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasEspacosSpaceIdRoute = TarefasEspacosSpaceIdRouteImport.update({
  id: '/tarefas/espacos/$spaceId',
  path: '/tarefas/espacos/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasQuadrosBoardIdRoute = TarefasQuadrosBoardIdRouteImport.update({
  id: '/tarefas/quadros/$boardId',
  path: '/tarefas/quadros/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/conta': typeof ContaRoute
  '/convite': typeof ConviteRoute
  '/importar': typeof ImportarRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/pendentes': typeof PendentesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/transacoes': typeof TransacoesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/api/health': typeof ApiHealthRoute
  '/tarefas/agenda': typeof TarefasAgendaRoute
  '/tarefas/calendario': typeof TarefasCalendarioRoute
  '/tarefas/meu-dia': typeof TarefasMeuDiaRoute
  '/tarefas/minhas': typeof TarefasMinhasRoute
  '/tarefas/todas': typeof TarefasTodasRoute
  '/admin/': typeof AdminIndexRoute
  '/tarefas/': typeof TarefasIndexRoute
  '/api/cakto/webhook': typeof ApiCaktoWebhookRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/sync': typeof ApiGoogleSyncRoute
  '/tarefas/espacos/$spaceId': typeof TarefasEspacosSpaceIdRoute
  '/tarefas/quadros/$boardId': typeof TarefasQuadrosBoardIdRoute
  '/tarefas/espacos/': typeof TarefasEspacosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/conta': typeof ContaRoute
  '/convite': typeof ConviteRoute
  '/importar': typeof ImportarRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/pendentes': typeof PendentesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/transacoes': typeof TransacoesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/api/health': typeof ApiHealthRoute
  '/tarefas/agenda': typeof TarefasAgendaRoute
  '/tarefas/calendario': typeof TarefasCalendarioRoute
  '/tarefas/meu-dia': typeof TarefasMeuDiaRoute
  '/tarefas/minhas': typeof TarefasMinhasRoute
  '/tarefas/todas': typeof TarefasTodasRoute
  '/admin': typeof AdminIndexRoute
  '/tarefas': typeof TarefasIndexRoute
  '/api/cakto/webhook': typeof ApiCaktoWebhookRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/sync': typeof ApiGoogleSyncRoute
  '/tarefas/espacos/$spaceId': typeof TarefasEspacosSpaceIdRoute
  '/tarefas/quadros/$boardId': typeof TarefasQuadrosBoardIdRoute
  '/tarefas/espacos': typeof TarefasEspacosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/conta': typeof ContaRoute
  '/convite': typeof ConviteRoute
  '/importar': typeof ImportarRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/pendentes': typeof PendentesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/transacoes': typeof TransacoesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/api/health': typeof ApiHealthRoute
  '/tarefas/agenda': typeof TarefasAgendaRoute
  '/tarefas/calendario': typeof TarefasCalendarioRoute
  '/tarefas/meu-dia': typeof TarefasMeuDiaRoute
  '/tarefas/minhas': typeof TarefasMinhasRoute
  '/tarefas/todas': typeof TarefasTodasRoute
  '/admin/': typeof AdminIndexRoute
  '/tarefas/': typeof TarefasIndexRoute
  '/api/cakto/webhook': typeof ApiCaktoWebhookRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/sync': typeof ApiGoogleSyncRoute
  '/tarefas/espacos/$spaceId': typeof TarefasEspacosSpaceIdRoute
  '/tarefas/quadros/$boardId': typeof TarefasQuadrosBoardIdRoute
  '/tarefas/espacos/': typeof TarefasEspacosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinatura'
    | '/auth'
    | '/categorias'
    | '/conta'
    | '/convite'
    | '/importar'
    | '/investimentos'
    | '/metas'
    | '/pendentes'
    | '/redefinir-senha'
    | '/transacoes'
    | '/admin/eventos'
    | '/api/health'
    | '/tarefas/agenda'
    | '/tarefas/calendario'
    | '/tarefas/meu-dia'
    | '/tarefas/minhas'
    | '/tarefas/todas'
    | '/admin/'
    | '/tarefas/'
    | '/api/cakto/webhook'
    | '/api/google/callback'
    | '/api/google/sync'
    | '/tarefas/espacos/$spaceId'
    | '/tarefas/quadros/$boardId'
    | '/tarefas/espacos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinatura'
    | '/auth'
    | '/categorias'
    | '/conta'
    | '/convite'
    | '/importar'
    | '/investimentos'
    | '/metas'
    | '/pendentes'
    | '/redefinir-senha'
    | '/transacoes'
    | '/admin/eventos'
    | '/api/health'
    | '/tarefas/agenda'
    | '/tarefas/calendario'
    | '/tarefas/meu-dia'
    | '/tarefas/minhas'
    | '/tarefas/todas'
    | '/admin'
    | '/tarefas'
    | '/api/cakto/webhook'
    | '/api/google/callback'
    | '/api/google/sync'
    | '/tarefas/espacos/$spaceId'
    | '/tarefas/quadros/$boardId'
    | '/tarefas/espacos'
  id:
    | '__root__'
    | '/'
    | '/assinatura'
    | '/auth'
    | '/categorias'
    | '/conta'
    | '/convite'
    | '/importar'
    | '/investimentos'
    | '/metas'
    | '/pendentes'
    | '/redefinir-senha'
    | '/transacoes'
    | '/admin/eventos'
    | '/api/health'
    | '/tarefas/agenda'
    | '/tarefas/calendario'
    | '/tarefas/meu-dia'
    | '/tarefas/minhas'
    | '/tarefas/todas'
    | '/admin/'
    | '/tarefas/'
    | '/api/cakto/webhook'
    | '/api/google/callback'
    | '/api/google/sync'
    | '/tarefas/espacos/$spaceId'
    | '/tarefas/quadros/$boardId'
    | '/tarefas/espacos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AuthRoute: typeof AuthRoute
  CategoriasRoute: typeof CategoriasRoute
  ContaRoute: typeof ContaRoute
  ConviteRoute: typeof ConviteRoute
  ImportarRoute: typeof ImportarRoute
  InvestimentosRoute: typeof InvestimentosRoute
  MetasRoute: typeof MetasRoute
  PendentesRoute: typeof PendentesRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TransacoesRoute: typeof TransacoesRoute
  AdminEventosRoute: typeof AdminEventosRoute
  ApiHealthRoute: typeof ApiHealthRoute
  TarefasAgendaRoute: typeof TarefasAgendaRoute
  TarefasCalendarioRoute: typeof TarefasCalendarioRoute
  TarefasMeuDiaRoute: typeof TarefasMeuDiaRoute
  TarefasMinhasRoute: typeof TarefasMinhasRoute
  TarefasTodasRoute: typeof TarefasTodasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TarefasIndexRoute: typeof TarefasIndexRoute
  ApiCaktoWebhookRoute: typeof ApiCaktoWebhookRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiGoogleSyncRoute: typeof ApiGoogleSyncRoute
  TarefasEspacosSpaceIdRoute: typeof TarefasEspacosSpaceIdRoute
  TarefasQuadrosBoardIdRoute: typeof TarefasQuadrosBoardIdRoute
  TarefasEspacosIndexRoute: typeof TarefasEspacosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendentes': {
      id: '/pendentes'
      path: '/pendentes'
      fullPath: '/pendentes'
      preLoaderRoute: typeof PendentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/': {
      id: '/tarefas/'
      path: '/tarefas'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof TarefasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/agenda': {
      id: '/tarefas/agenda'
      path: '/tarefas/agenda'
      fullPath: '/tarefas/agenda'
      preLoaderRoute: typeof TarefasAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/calendario': {
      id: '/tarefas/calendario'
      path: '/tarefas/calendario'
      fullPath: '/tarefas/calendario'
      preLoaderRoute: typeof TarefasCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/meu-dia': {
      id: '/tarefas/meu-dia'
      path: '/tarefas/meu-dia'
      fullPath: '/tarefas/meu-dia'
      preLoaderRoute: typeof TarefasMeuDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/minhas': {
      id: '/tarefas/minhas'
      path: '/tarefas/minhas'
      fullPath: '/tarefas/minhas'
      preLoaderRoute: typeof TarefasMinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/todas': {
      id: '/tarefas/todas'
      path: '/tarefas/todas'
      fullPath: '/tarefas/todas'
      preLoaderRoute: typeof TarefasTodasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cakto/webhook': {
      id: '/api/cakto/webhook'
      path: '/api/cakto/webhook'
      fullPath: '/api/cakto/webhook'
      preLoaderRoute: typeof ApiCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/sync': {
      id: '/api/google/sync'
      path: '/api/google/sync'
      fullPath: '/api/google/sync'
      preLoaderRoute: typeof ApiGoogleSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/espacos/': {
      id: '/tarefas/espacos/'
      path: '/tarefas/espacos'
      fullPath: '/tarefas/espacos/'
      preLoaderRoute: typeof TarefasEspacosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/espacos/$spaceId': {
      id: '/tarefas/espacos/$spaceId'
      path: '/tarefas/espacos/$spaceId'
      fullPath: '/tarefas/espacos/$spaceId'
      preLoaderRoute: typeof TarefasEspacosSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/quadros/$boardId': {
      id: '/tarefas/quadros/$boardId'
      path: '/tarefas/quadros/$boardId'
      fullPath: '/tarefas/quadros/$boardId'
      preLoaderRoute: typeof TarefasQuadrosBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinaturaRoute: AssinaturaRoute,
  AuthRoute: AuthRoute,
  CategoriasRoute: CategoriasRoute,
  ContaRoute: ContaRoute,
  ConviteRoute: ConviteRoute,
  ImportarRoute: ImportarRoute,
  InvestimentosRoute: InvestimentosRoute,
  MetasRoute: MetasRoute,
  PendentesRoute: PendentesRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TransacoesRoute: TransacoesRoute,
  AdminEventosRoute: AdminEventosRoute,
  ApiHealthRoute: ApiHealthRoute,
  TarefasAgendaRoute: TarefasAgendaRoute,
  TarefasCalendarioRoute: TarefasCalendarioRoute,
  TarefasMeuDiaRoute: TarefasMeuDiaRoute,
  TarefasMinhasRoute: TarefasMinhasRoute,
  TarefasTodasRoute: TarefasTodasRoute,
  AdminIndexRoute: AdminIndexRoute,
  TarefasIndexRoute: TarefasIndexRoute,
  ApiCaktoWebhookRoute: ApiCaktoWebhookRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiGoogleSyncRoute: ApiGoogleSyncRoute,
  TarefasEspacosSpaceIdRoute: TarefasEspacosSpaceIdRoute,
  TarefasQuadrosBoardIdRoute: TarefasQuadrosBoardIdRoute,
  TarefasEspacosIndexRoute: TarefasEspacosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
