REVOKE EXECUTE ON FUNCTION public.account_role(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_account_member(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.can_edit_account(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_account_owner(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.profile_account(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.add_owner_member() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.accept_account_invite(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.invite_preview(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.accept_account_invite(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.invite_preview(uuid) TO authenticated;